#!/bin/bash

git submodule init
git submodule foreach git fetch
git submodule update


echo
if [ "$1" = "--hard" ]; then
	echo "    Resetting HARD to latest cling refs"
else
	echo "    Checking out committed submodule refs"
	echo "    Use --hard do get latest Cling changes (local changes will be lost)"
fi
echo


function cling_patches {
    echo Getting Cling patched
	cd $1
	git remote add cling http://root.cern.ch/git/$1.git
	git fetch cling
	if [ "$2" = "--hard" ]; then
		git reset --hard cling/cling-patches
	fi
	cd ..
}
cling_patches llvm  $1
cling_patches clang $1




if [ "$1" = "--hard" ]; then
	cd cling
		git reset --hard origin/master
	cd ..
else
	git submodule update
fi




function check_link {
    if [ ! -d "$2" ]; then
        echo Creating symbolic link $2 to $PWD/$1
        ln  -s $PWD/$1 $2
    fi
}
check_link cling        llvm/tools/cling
check_link clang        llvm/tools/clang
check_link compiler-rt  llvm/projects/compiler-rt



# show summary
git status

